/* eslint-disable @typescript-eslint/no-explicit-any */
import { norm, type PGraph } from './graph';
import { modelOf } from './spec';
import { TEMPLATES, type PackKind } from './templates';

/**
 * Sandbox configuration for a process (plan §19). Generated only: no sandbox is provisioned or executed in this
 * release. Baseline schema is listed before deltas, in order.
 */
export function sandboxConfig(g: PGraph, pi: number, spec: any, opt: { source: string; vertical: string }): any {
  const pr = g.processes[pi]!, M = modelOf(g);
  const files = Object.values(g.files);
  const roots = [...new Set(files.filter((f) => /\.(cls|p|i|w)$/.test(f.path)).map((f) => f.path.split('/')[0]!))];
  const dfs = files.filter((f) => f.kind === 'schema').map((f) => f.path).sort();
  const baseline = dfs.filter((p) => !/delta|migration/i.test(p));
  const deltas = dfs.filter((p) => /delta/i.test(p));
  const seeds = files.filter((f) => /seed/i.test(f.path) && /\.p$/.test(f.path)).map((f) => f.path);
  const tests = [...new Set(spec.steps.flatMap((s: any) => s.trace.tests))];
  const hasBuild = files.some((f) => /build\.xml$/.test(f.path)) || g.raw.some((r) => /build\.xml$/.test(r.path));
  const slug = pr.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return {
    apiVersion: 'lens.mip/v1', kind: 'SandboxConfig',
    metadata: { name: `${norm(opt.source)}-${slug}`, process: pr.name, source: opt.source, vertical: opt.vertical, generatedAt: spec.generated, generatedFrom: `commit ${g.meta.head || 'unknown'}` },
    source: { repository: opt.source, commit: g.meta.head || null, propath: roots.includes('src') ? ['src', ...roots.filter((r) => r !== 'src')] : roots },
    runtime: { platform: 'OpenEdge', agent: 'PASOE', compile: hasBuild ? 'ant -f tooling/build.xml compile' : 'pct compile (whole PROPATH)' },
    database: { name: `sbx_${norm(slug).slice(0, 20)}`, create: 'prodb {name} empty', schema: baseline, deltasInOrder: deltas, load: 'proutil {name} -C LOAD-DF {file}', seed: seeds, tablesUsed: [...new Set(pr.stages.flatMap((st) => st.tables))], dataPolicy: 'Synthetic data only. Never load production personal data (POPIA).' },
    roles: M.roles.map((r: string) => ({ role: r, testUser: `sbx_${r.toLowerCase()}` })),
    steps: spec.steps.map((s: any) => ({ step: +s.n, name: s.title, requirement: s.trace.req, entryFiles: s.trace.files, tables: s.trace.tables, rules: s.trace.rules, gatedRoles: (s.screen.action || {}).roles || [], fixture: Object.fromEntries(Object.entries(spec.sample).filter(([k]) => (s.screen.fields || []).some((d: any) => d.k === k) || (s.screen.list && s.screen.list.k === k))) })),
    businessRules: [...new Set(pr.stages.flatMap((st) => st.rules))].map((c) => ({ code: c, description: (M.ruleInfo[c] || {}).desc || (g.rulecodes[c] || {}).title || '', class: (M.ruleInfo[c] || {}).file || null, enabled: true })),
    tests: { suites: tests, command: `ablunit -directory tests -format xml -output build/ablunit-${slug}.xml` },
    regressionScenarios: [...new Map<string, any>(spec.steps.flatMap((s: any) => s.history.incidents.map((x: any) => [x.id, { incident: x.id, title: x.title, status: x.status, steps: spec.steps.filter((y: any) => y.history.incidents.some((z: any) => z.id === x.id)).map((y: any) => +y.n) }]))).values()],
    draftImplementation: { enabled: false, note: 'Filled by a change project when the sandbox feature is switched on: its impact list becomes the files to patch.' },
  };
}

export function toYaml(o: any, ind = ''): string {
  const q = (v: any) => typeof v === 'string' ? (v === '' || /[:#\-{}[\],&*?|<>=!%@`"'\n]|^\s|\s$|^(true|false|null|yes|no|\d.*)$/i.test(v) ? JSON.stringify(v) : v) : v === null ? 'null' : String(v);
  if (Array.isArray(o)) return o.length ? o.map((v) => (v && typeof v === 'object') ? `${ind}-\n${toYaml(v, ind + '  ')}` : `${ind}- ${q(v)}`).join('\n') : `${ind}[]`;
  return Object.entries(o).map(([k, v]: [string, any]) => {
    if (v && typeof v === 'object') { if (Array.isArray(v) && !v.length) return `${ind}${k}: []`; if (!Array.isArray(v) && !Object.keys(v).length) return `${ind}${k}: {}`; return `${ind}${k}:\n${toYaml(v, ind + '  ')}`; }
    return `${ind}${k}: ${q(v)}`;
  }).join('\n');
}

export function docMarkdown(spec: any): string {
  const T: Record<string, string> = { gate: 'Gate', data: 'Data', rule: 'Rule', q: 'Open question' };
  const L: string[] = [`# ${spec.title}`, '', `*${spec.vertical}, ${spec.source}. Generated by Lens from commit ${spec.commit || 'unknown'} on ${String(spec.generated).slice(0, 10)}.*`, '', spec.intro, '', '## The journey', '', ...spec.steps.map((s: any) => `${+s.n}. **${s.title}** (${spec.phases[s.ph]})`), ''];
  for (const s of spec.steps) {
    L.push(`## ${s.n}. ${s.title}`, '', s.say, '');
    if (s.badge) L.push(`> **${s.badge[0]}:** ${s.badge[1]}`, '');
    if (s.rules.length) L.push(...s.rules.map((r: any) => `- **${T[r[0]] || r[0]}:** ${r[1]}`), '');
    const f = (s.screen.fields || []).filter((d: any) => d.type !== 'computed' || d.sample);
    if (f.length) L.push('| Field | Type | Required | Sample | Stored in |', '|---|---|---|---|---|', ...f.map((d: any) => `| ${d.label} | ${d.type} | ${d.required ? 'yes' : ''} | ${d.sample || ''} | ${d.k} |`), '');
    if (s.screen.list) L.push(`Choose from: ${s.screen.list.options.map((o: any) => `${o.code}${o.amt != null ? ` (R${o.amt})` : ''}${o.off ? ' (inactive)' : ''}`).join(', ')}`, '');
    if (s.screen.checks) L.push('| Rule | What it checks |', '|---|---|', ...s.screen.checks.map((c: any) => `| ${c.code} | ${c.text} |`), '');
    L.push(`Behind the screen: requirement ${s.trace.req || 'none matched'}; rules ${s.trace.rules.join(', ') || 'none'}; code ${s.trace.files.join(', ') || 'none matched'}; tests ${s.trace.tests.join(', ') || 'none'}.`, '');
    if (s.history.changes.length || s.history.incidents.length) L.push('History:', ...s.history.changes.map((c: any) => `- ${c.date} ${c.subject} (${c.id}${c.ticket ? ', ' + c.ticket : ''})`), ...s.history.incidents.map((x: any) => `- ${x.id} ${x.title} (${x.status || ''})`), '');
  }
  if (spec.openQuestions.length) L.push('## Open questions', '', ...spec.openQuestions.map((q: string) => `- ${q}`), '');
  return L.join('\n');
}

/** JSON embedded in a <script>: `<` is escaped so spec text (rule messages, commit subjects) can never close the script tag. */
export const embedSpec = (spec: unknown) => JSON.stringify(spec).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');

export type Theme = 'light' | 'dark';

/** Standalone HTML artefact. The selected theme is passed in via data-theme (plan §20). */
export function artefactHtml(kind: PackKind, spec: any, theme: Theme = 'light'): string {
  const brand = /^#[0-9A-Fa-f]{3,8}$/.test(spec.brand) ? spec.brand : '#0A5BC4';
  return TEMPLATES[kind].replace('__SPEC__', () => embedSpec(spec)).replace(/__BRAND__/g, brand).replace(/<html lang="en">/, `<html lang="en" data-theme="${theme}">`);
}

/** Attribute for the viewer iframe. No same-origin access (plan §19): scripts run, but with an opaque origin. */
export const PACK_IFRAME_SANDBOX = 'allow-scripts';
