/* eslint-disable @typescript-eslint/no-explicit-any */
import fs from 'node:fs';
import path from 'node:path';
import { describe, it, expect, beforeAll } from 'vitest';
import { loadFixture } from '../../../test/helpers/fixture';
import type { ModelClient } from '@lens/ai';
import { toPackGraph, buildSpec, sandboxConfig, toYaml, docMarkdown, artefactHtml, embedSpec, sanitizeRefinement, specHash, refineWording, SpecCache, PACK_IFRAME_SANDBOX, type PGraph } from '../src';

let g: PGraph; let spec: any; let cfg: any; let ref: any;
const opt = { source: 'BafozAIChallenge-project', vertical: 'Personal Insurance' };

beforeAll(async () => {
  const fx = await loadFixture();
  g = toPackGraph({
    graph: fx.graph, view: fx.view, files: fx.source, commits: fx.commits,
    tickets: fx.tickets.map((t) => ({ key: t.key, commit: t.commit })),
    incidents: fx.incidents.map((n) => ({ key: n.key, title: n.title, status: n.status, severity: n.severity, rootCause: n.rootCause, files: n.resolved.map((r) => r.resolved ?? r.input), reqs: n.reqs })),
  });
  ref = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../../test/fixtures/prototype-pack-reference.json'), 'utf8'));
  spec = buildSpec(g, 0, { ...opt, generatedAt: ref.spec.generated });
  cfg = sandboxConfig(g, 0, spec, opt);
});

describe("parity with the prototype (reference generated by the prototype's own code on the same repository)", () => {
  it('process spec is identical', () => expect(spec).toEqual(ref.spec));
  it('sandbox config, YAML and Markdown are identical', () => {
    expect(cfg).toEqual(ref.cfg);
    expect(toYaml(cfg)).toBe(ref.yaml);
    expect(docMarkdown(spec)).toBe(ref.md);
  });
});

describe('process spec facts (M10)', () => {
  it('covers the 7 New Business steps in four phases', () => {
    expect(spec.steps).toHaveLength(7);
    expect(spec.phases).toEqual(['Start', 'Capture', 'Check', 'Complete']);
  });
  it('NB-COLLECTION-002 rejects day 31 for monthly debit orders and accepts day 25', () => {
    const check = spec.steps[5].screen.checks.find((c: any) => c.code === 'NB-COLLECTION-002');
    const range = check.conds[0].ranges.find((r: any) => r.when?.vals.includes('DEBIT_ORDER'));
    expect([range.min, range.max]).toEqual([1, 28]);
    expect(31 >= range.min && 31 <= range.max).toBe(false);
    expect(25 >= range.min && 25 <= range.max).toBe(true);
  });
  it('activation is gated to SUPERVISOR or ADMIN and needs a passed validation', () => {
    const a = spec.steps[6].screen.action;
    expect(a.roles).toEqual(['SUPERVISOR', 'ADMIN']);
    expect(a.needsValidation).toBe(true);
    expect([a.from, a.to]).toEqual(['NEW', 'IN-FORCE']);
  });
  it('sample data is synthetic and the incident shows up as an open question', () => {
    expect(JSON.stringify(spec.sample)).toContain('Sizwe');
    expect(spec.openQuestions.some((q: string) => q.startsWith('INC-2291'))).toBe(true);
  });
  it('choices come from seed data and STATIC PROPERTY ... INITIAL; ID prefixes from SUBSTITUTE', () => {
    expect(spec.steps[3].screen.list.options.length).toBeGreaterThan(1);
    expect(spec.sample['Contract.ContractId']).toBe('CON-000001');
    const method = spec.steps.flatMap((s: any) => s.screen.fields ?? []).find((d: any) => d.k === 'CollectionInstruction.CollectionMethod');
    expect(method.options.map((o: any) => o.v)).toEqual(expect.arrayContaining(['DEBIT_ORDER', 'PAYROLL']));
  });
});

describe('sandbox config (generated, never executed)', () => {
  it('lists the baseline schema before the deltas, in order, and the seed procedure', () => {
    expect(cfg.database.schema).toEqual(['database/schema/newbusiness.df']);
    expect(cfg.database.deltasInOrder).toEqual(['database/delta/002_benefit_cover_amount.df', 'database/delta/003_contract_sequence.df']);
    expect(cfg.database.seed).toEqual(['database/seed/SeedData.p']);
    expect(cfg.database.dataPolicy).toMatch(/Synthetic data only/);
  });
  it('carries roles, rules and a disabled draft-implementation block', () => {
    expect(cfg.roles.map((r: any) => r.role)).toEqual(['NEW_BUSINESS_AGENT', 'SUPERVISOR', 'ADMIN']);
    expect(cfg.businessRules.map((r: any) => r.code)).toContain('NB-COLLECTION-002');
    expect(cfg.draftImplementation.enabled).toBe(false);
    expect(cfg.regressionScenarios.map((r: any) => r.incident)).toContain('INC-2291');
  });
  it('YAML quotes ambiguous scalars', () => {
    expect(toYaml({ a: 'yes', b: '1.0', c: 'x: y', d: [], e: {}, f: null })).toBe('a: "yes"\nb: "1.0"\nc: "x: y"\nd: []\ne: {}\nf: null');
  });
});

describe('rendering', () => {
  it('embeds the spec safely: a spec containing a closing script tag cannot break out of the page', () => {
    const evil = { ...spec, intro: '</script><script>alert(1)</script>' };
    const html = artefactHtml('doc', evil);
    expect(embedSpec(evil)).not.toContain('<');
    expect(html).not.toContain('</script><script>alert');
  });
  it('passes the selected theme and a validated brand colour into the HTML', () => {
    expect(artefactHtml('explainer', spec, 'dark')).toContain('<html lang="en" data-theme="dark">');
    expect(artefactHtml('prototype', { ...spec, brand: 'red;}</style><script>x' })).not.toContain('</style><script>x');
    for (const k of ['doc', 'explainer', 'prototype'] as const) { const h = artefactHtml(k, spec); expect(h).not.toContain('__SPEC__'); expect(h).not.toContain('__BRAND__'); }
  });
  it('the viewer iframe sandbox grants scripts but not same-origin', () => {
    expect(PACK_IFRAME_SANDBOX).toBe('allow-scripts');
    expect(PACK_IFRAME_SANDBOX).not.toContain('same-origin');
  });
});

describe('wording refinement cannot change facts', () => {
  const good = () => ({ steps: spec.steps.map((s: any) => ({ n: +s.n, title: `Nice ${s.title}`, say: 'Plain words.', rules: s.rules.map(([t, x]: [string, string]) => [t, x.replace(/^([A-Z]+-[A-Z]+-\d+): /, '$1: Friendly ')]), chips: s.chips.map(([k, x]: [string, string]) => [k, x.toLowerCase()]) })) });
  it('accepts pure rewording', () => {
    const r = sanitizeRefinement(spec, good());
    expect(r.rejected).toEqual([]);
    expect(r.steps).toHaveLength(7);
  });
  it('rejects refined rules that drop or invent rule/incident ids, or change the number of rules', () => {
    const bad: any = good();
    bad.steps[4].rules = bad.steps[4].rules.map(([t, x]: [string, string]) => [t, x.replace('NB-COLLECTION-002', 'NB-MADE-UP-999')]);
    bad.steps[5].rules.pop();
    const r = sanitizeRefinement(spec, bad);
    expect(r.steps.find((s) => s.n === 5)!.rules).toBeUndefined();
    expect(r.steps.find((s) => s.n === 6)!.rules).toBeUndefined();
    expect(r.rejected.length).toBe(2);
  });
  it('rejects chips with changed keys and steps that do not exist', () => {
    const bad: any = good();
    bad.steps[0].chips[0][0] = 'other';
    bad.steps.push({ n: 99, title: 'x' });
    const r = sanitizeRefinement(spec, bad);
    expect(r.steps.find((s) => s.n === 1)!.chips).toBeUndefined();
    expect(r.rejected.some((x) => x.includes('99'))).toBe(true);
  });
  it('an applied override changes wording only: the fact hash, screens, trace and history are unchanged', () => {
    const before = specHash(spec);
    const refined = buildSpec(g, 0, { ...opt, generatedAt: spec.generated, override: { steps: sanitizeRefinement(spec, good()).steps } });
    expect(refined.refined).toBe(true);
    expect(refined.steps[0].title).toMatch(/^Nice /);
    expect(specHash(refined)).toBe(before);
    for (let i = 0; i < 7; i++) for (const k of ['screen', 'trace', 'history', 'n', 'ph']) expect(refined.steps[i][k]).toEqual(spec.steps[i][k]);
    expect(refined.sample).toEqual(spec.sample);
  });
  it('a factual change in the code changes the fact hash (so stale overrides are detectable)', () => {
    const g2: PGraph = structuredClone(g);
    g2.commits.pop(); g2.processes[0]!.stages[0]!.tables = [];
    expect(specHash(buildSpec(g2, 0, { ...opt, generatedAt: spec.generated }))).not.toBe(specHash(spec));
  });
  it('refineWording makes one tool-less call, fences the facts, and sanitises the reply', async () => {
    let seen: any; let calls = 0;
    const model: ModelClient = { provider: 't', model: 't', async complete(r) { calls++; seen = r; return { content: [{ type: 'text', text: JSON.stringify(good()) }], stopReason: 'end_turn', usage: { inputTokens: 5, outputTokens: 6 } }; } };
    const out = await refineWording(spec, Object.fromEntries(Object.values(g.requirements).map((r) => [r.id, r.body])), model);
    expect(calls).toBe(1);
    expect(seen.tools).toBeUndefined();
    expect(seen.messages[0].content).toMatch(/<untrusted-[0-9a-f]+/);
    expect(out.refinement.steps).toHaveLength(7);
  });
});

describe('spec cache', () => {
  it('is keyed by process + snapshot SHA and regenerates after a new snapshot', () => {
    const c = new SpecCache();
    const a = c.get(g, 0, 'sha1', { ...opt, generatedAt: 'x' }), b = c.get(g, 0, 'sha1', { ...opt, generatedAt: 'y' });
    expect(b).toBe(a);
    expect(c.get(g, 0, 'sha2', { ...opt, generatedAt: 'z' })).not.toBe(a);
    expect(c.size).toBe(2);
  });
});
